import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:parentteach/screen/home_screen.dart';
//import 'package:parentteach/screen/login_screen.dart';
import 'package:parentteach/screen/login_screencopy.dart';
import 'package:parentteach/screen/onboarding_screen.dart';
import 'package:parentteach/screen/profile_screen.dart';
import 'package:parentteach/screen/registration_screencopy.dart';
import 'package:parentteach/screen/splash_screen.dart';
//import 'firebase_options.dart';
//import 'screen/auth_screen.dart';
import 'screen/solution_screen.dart'; // generated by the FlutterFire CLI

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (kIsWeb) {
    await Firebase.initializeApp(
      options: FirebaseOptions(
          apiKey: "AIzaSyB-cBXpp6HBZtnipZzv3qUVXLzCGEB0gYY",
          appId: "1:359600546456:web:38784de513c9e009e066ed",
          messagingSenderId: "359600546456",
          projectId: "parentteach-firebase"),
    );
  }

  await Firebase.initializeApp();

  runApp(MyApp());
}
//import 'package:firebase_core/firebase_core.dart';

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(seedColor: const Color.fromARGB(255, 6, 6, 111),),
      ),      
      //home: const SplashScreen(),
      home: const HomeScreen(),
      //home: ProfileScreen(),

    );
  }
}